import {Suspense} from 'react'
import { Inter } from "next/font/google";
import Layout from '@/components/layout' // Layout コンポーネントをインポート
import "@/css/globals.css";

import {
  baseMetadata,
  openGraphMetadata,
  twitterMetadata,
} from '@/lib/baseMetadata'

//font Awesomeの設定
import '@fortawesome/fontawesome-svg-core/styles.css'
import {config} from '@fortawesome/fontawesome-svg-core'
config.autoAddCss = false

import { siteMeta } from '@/lib/constants'
const { siteLang } = siteMeta

const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

import Script from 'next/script'; // next/scriptをインポート

import GoogleAnalytics from '@/components/googleanalytics'


export default function RootLayout({ children }) {
  return (
    <html lang={siteLang}>
      <body className={inter.className}>
      <Script src="/particles.js" strategy="beforeInteractive" />
        <Suspense>
        <GoogleAnalytics />
        </Suspense>
        <Layout>
          {children}      
        </Layout>
      </body>
    </html>
  );
}

export const metadata = {
  ...baseMetadata,
  openGraph: {
    ...openGraphMetadata,
  },
  twitter: {
    ...twitterMetadata,
  },
}

